config:
  line-length:
    line_length: 120
    #stern: true
    code_blocks: false

  headings: false

  proper-names:
    code_blocks: false
    names:
    - CommonMark
    - JavaScript
    - Markdown
    - markdown-it
    - markdownlint
    - markdownlint-cli2
    - Node.js

fix: true
